### ISSUE TITLE
Coverage API endpoint uses v1, which is depreciated.

### ISSUE THREAD

**Issue by tbekri** [sigfox/sigfox-network-test#2]
network-test.js line 58 needs to be changed to
      url: 'http://backend.sigfox.com/api/v2/coverages/global/predictions?lat='+lat + '&lng=' + lng,

**Comment by nicolsc** [comment]
@tbekri  Can you check & confirm it works now ?

I switched to API v2 following your comment + fixed security issues on a couple packages as raised by github + switched to dotenv for the config file

**Comment by tbekri** [comment]
All good @nicolsc thanks for prompt response.
